import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "../components/layout/MainLayout";
import GlobalProvider from "../components/providers/GlobalProvider";


export const metadata: Metadata = {
  title: { 
    absolute: "Pagina Inicial | Yosso", 
    template: "%s | Yosso" 
  },
  description: "Generated by create next app",
  icons:{
    icon: ["/favicon.ico?v=4"],
    apple: ["/images/icons/favicon/apple-touch-icon.png"],
    shortcut: ["/images/icons/favicon/apple-touch-icon.png"]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-AO">
      <body>
        <GlobalProvider>
          <MainLayout>
            {children}
          </MainLayout>
        </GlobalProvider>
      </body>
    </html>
  );
}
