import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import GlobalProvider from "@/components/providers/GlobalProvider";


export const metadata: Metadata = {
  title: { 
    absolute: "Pagina Inicial", 
    template: "%s | Yosso Finanças" 
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-AO">
      <body>
        <GlobalProvider>
          <MainLayout>
            {children}
          </MainLayout>
        </GlobalProvider>
      </body>
    </html>
  );
}
